ISSI_BATCHES = [
    # BATCH 1
    [
        "AALI.JK","ABBA.JK","ACES.JK","ACST.JK","ADES.JK","ADHI.JK","ADMG.JK","ADRO.JK","AGAR.JK","AGII.JK",
"AKKU.JK","AKPI.JK","AKRA.JK","AKSI.JK","ALDO.JK","ALKA.JK","ALMI.JK","AMAG.JK","AMFG.JK","AMRT.JK",
"ANDI.JK","ANTM.JK","APEX.JK","APIC.JK","ARCI.JK","ARKA.JK","ARNA.JK","ARTA.JK","ARTI.JK","ASBI.JK",
"ASDM.JK","ASGR.JK","ASII.JK","ASMI.JK","ASRI.JK","ATIC.JK","AUTO.JK","BABP.JK","BACA.JK","BAJA.JK",
"BBHI.JK","BBKP.JK","BBMD.JK","BBYB.JK","BCIC.JK","BEBS.JK","BEEF.JK","BELL.JK","BFIN.JK","BHAT.JK",
"BIMA.JK","BINA.JK","BIPI.JK","BIRD.JK","BJBR.JK","BJTM.JK","BKSL.JK","BMAS.JK","BNBA.JK","BNGA.JK",
"BOGA.JK","BOLA.JK","BRIS.JK","BRMS.JK","BRPT.JK","BSDE.JK","BSML.JK","BUKA.JK","BULL.JK","BWPT.JK",
"CAMP.JK","CARE.JK","CASA.JK","CBMF.JK","CEKA.JK","CENT.JK","CFIN.JK","CINT.JK","CLAY.JK","CMNP.JK",
"CNKO.JK","CNTX.JK","CPIN.JK","COWL.JK","CSAP.JK","CTRA.JK","DART.JK","DEAL.JK","DEFI.JK","DGNS.JK"
    ],

    # BATCH 2
    [
        "DILD.JK","DIVA.JK","DKFT.JK","DMAS.JK","DOID.JK","DPNS.JK","DRMA.JK","DSFI.JK","DSNG.JK","DSSA.JK",
"DUTI.JK","DVLA.JK","DYAN.JK","ECII.JK","EDGE.JK","ELSA.JK","EMTK.JK","ENRG.JK","ERAA.JK","ESSA.JK",
"ESTI.JK","EXCL.JK","FAPA.JK","FAST.JK","FIRE.JK","FORU.JK","GAMA.JK","GEMS.JK","GIAA.JK","GJTL.JK",
"GLOB.JK","GOTO.JK","GPRA.JK","GREN.JK","GSMF.JK","HART.JK","HMSP.JK","HOPE.JK","HRUM.JK","IBOS.JK",
"ICON.JK","IMAS.JK","IMPC.JK","INAI.JK","INCO.JK","INDF.JK","INDR.JK","INKP.JK","INPC.JK","INPP.JK",
"INTA.JK","IPOL.JK","ISAT.JK","ITIC.JK","ITMG.JK","JAWA.JK","JECC.JK","JPFA.JK","JRPT.JK","JSMR.JK",
"JTPE.JK","KAEF.JK","KARW.JK","KBLM.JK","KBRI.JK","KBLI.JK","KDSI.JK","KIJA.JK","KKGI.JK","KLBF.JK",
"KOIN.JK","KONI.JK","KPIG.JK","KRAS.JK","LAPD.JK","LCGP.JK","LION.JK","LMPI.JK","LPCK.JK","LPGI.JK",
"LSIP.JK","LTLS.JK","LUCK.JK","MABA.JK","MAIN.JK","MAPI.JK","MARK.JK","MASA.JK","MBSS.JK","MDIA.JK"
    ],

    # BATCH 3
    [
        "MDKA.JK","MDLN.JK","MEGA.JK","MFIN.JK","MICE.JK","MKPI.JK","MLBI.JK","MLIA.JK","MNCN.JK","MPMX.JK",
"MREI.JK","MSKY.JK","MTDL.JK","MTEL.JK","MYOR.JK","NELY.JK","NIKL.JK","NISP.JK","NINE.JK","NOBU.JK",
"NRCA.JK","OBAT.JK","OKAS.JK","OMRE.JK","OPMS.JK","PADI.JK","PANR.JK","PBID.JK","PDES.JK","PGAS.JK",
"PGEO.JK","PNBN.JK","PNIN.JK","POLY.JK","PRDA.JK","PSAB.JK","PTBA.JK","PTPP.JK","PURE.JK","PWON.JK",
"RAJA.JK","RALS.JK","RANC.JK","RDTX.JK","REAL.JK","RIMO.JK","RMBA.JK","ROTI.JK","SAFE.JK","SAME.JK",
"SAMF.JK","SCBD.JK","SDPC.JK","SDRA.JK","SICO.JK","SIDO.JK","SIMP.JK","SIPD.JK","SKBM.JK","SMAR.JK",
"SMDR.JK","SMGR.JK","SMRA.JK","SOCI.JK","SONA.JK","SPTO.JK","SQMI.JK","SRIL.JK","SRTG.JK","SSIA.JK",
"STAR.JK","SUGI.JK","SUPR.JK","TAMU.JK","TCID.JK","TFAS.JK","TGKA.JK","TINS.JK","TIRA.JK","TKIM.JK"
    ],

    # BATCH 4
    [
        "TLKM.JK","TMAS.JK","TOPS.JK","TOTL.JK","TOYS.JK","TPIA.JK","TRAM.JK","TRIN.JK","TRIS.JK","TRUK.JK",
"TSPC.JK","ULTJ.JK","UNIC.JK","UNSP.JK","URBN.JK","VICO.JK","WAPO.JK","WICO.JK","WIIM.JK","WIKA.JK",
"WOOD.JK","ZATA.JK","AMMN.JK","DCII.JK","BYAN.JK","BRPT.JK","ESSA.JK","HRUM.JK","ADRO.JK","ITMG.JK",
"PTBA.JK","TINS.JK","ANTM.JK","INCO.JK","MDKA.JK","NIKL.JK","GOTO.JK","BUKA.JK","EXCL.JK","ISAT.JK",
"ERAA.JK","MAPI.JK","MYOR.JK","ICBP.JK","KLBF.JK","SIDO.JK","CPIN.JK","JPFA.JK","SMGR.JK","TLKM.JK",
"PGAS.JK","PGEO.JK","MTEL.JK","TBIG.JK","TOWR.JK","PWON.JK","BSDE.JK","CTRA.JK","DMAS.JK","SSIA.JK",
"WEGE.JK","WTON.JK","PTPP.JK","PPRE.JK","SMRA.JK","DUTI.JK","KIJA.JK","BKSL.JK","APLN.JK","LAND.JK",
"RALS.JK","ACES.JK","FAST.JK","AMRT.JK","MPPA.JK","CSRA.JK","SERA.JK","TGRA.JK","PGUN.JK"
    ],

    # BATCH 5
    [
        "WIIM.JK","HMSP.JK","RMBA.JK","SURY.JK","GOOD.JK","CLEO.JK","KINO.JK","SKLT.JK","MLPL.JK","KOBX.JK",
"FOOD.JK","PCAR.JK","WMPP.JK","DMND.JK","IKAN.JK","BTEK.JK","NANO.JK","PACK.JK","ARGO.JK","POLA.JK"
"IPOL.JK","SOFA.JK","PEHA.JK","MENN.JK","COCO.JK","SIMP.JK","SGRO.JK","ANJT.JK","SSMS.JK","DSNG.JK"
"PALM.JK","BWPT.JK","LSIP.JK","AALI.JK","JAWA.JK","GOLL.JK","MINA.JK","KRYA.JK","HEXA.JK","BUDI.JK"
"SRSN.JK","SULI.JK","INTD.JK","GDST.JK","ENZO.JK","PRAS.JK","CNMA.JK","IBFN.JK","FUJI.JK","IPCC.JK"
"PORT.JK","SMRU.JK","APEX.JK","TIRA.JK","UNIC.JK","SUGI.JK","KRAH.JK","HRTA.JK","ALKA.JK","ALMI.JK"
"MLIA.JK","BAJA.JK","INDS.JK","AUTO.JK","BRAM.JK","GJTL.JK","MASA.JK","GDYR.JK","TRST.JK","LMSH.JK"
"KMTR.JK","SMSM.JK","TOTO.JK","INTP.JK","CMRY.JK","ULTJ.JK","CLEO.JK","IKBI.JK","LION.JK","NICE.JK"
    ]
]
ISSI_SYMBOLS = [sym for batch in ISSI_BATCHES for sym in batch]

ISSI_SYMBOLS = list(set(ISSI_SYMBOLS))
